openapi: 3.0.0
info:
  title: Api Documentation
  version: 1.0.0
servers:
  - url: http://127.0.0.1:8000
paths:
  /api/fp/items:
    get:
      summary: Get items
      responses:
        200:
          description: A list of items
          content:
            application/json:
  /api/fp/items/{item}:
    get:
      summary: Get item by id
      responses:
        200:
          description: A single item
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: The ID of the item
                  nama:
                    type: string
                    description: The name of the item
                  stok:
                    type: int
                    description: The author of the item
                  harga:
                    type: int
                    description: The author of the item
                  kategori:
                    type: array
                    description: The author of the item
                  deskripsi:
                    type: string
                    description: The author of the item

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
